dist: bionic # modern dist = Ruby 2.6x

language: ruby

cache: bundler

script:
  - bundle exec rubocop
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec

after_success:
  - openssl aes-256-cbc -K $encrypted_f8d167f54618_key -iv $encrypted_f8d167f54618_iv -in peach-deploy-key.enc -out ~/.ssh/peach-deploy-key -d
  - bundle exec cap production deploy
