version: '3'
services:
  server:
    build: ./docker/server
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
    ports:
      - "3000:3000"
    container_name: peach-server
    image: peach-melpa-server
  updater:
    build: ./docker/emacs
    environment:
      - RAILS_ENV=production
    container_name: peach-updater
    image: peach-melpa-updater
    depends_on:
      - server
    command: rake themes:all
  db:
    environment:
      - POSTGRES_DB=peach_prod
    image: postgres:latest
