name: CI

on: [push]

jobs:
  build:

    runs-on: ruby:2.6.5-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install gems
      run: bundle install
    - name: Run the tests
      run: |
        bundle exec rspec
        echo All good!
